import { demoUserPhotoUrl } from "@/config/site";
import type { Profile } from "../types";

export const mockProfiles: Profile[] = [
  {
    id: "p-ciro",
    name: "Ciro Ferrario",
    age: 31,
    headline:
      "Ingeniero Informático · Senior Software Engineer (Back-end) · Java · Laravel · Python",
    bio: "7 años diseñando y manteniendo sistemas backend: APIs REST, jobs, integraciones y bases de datos. Java y Spring en proyectos grandes, Laravel para productos ágiles, Python para automatización y tooling. Prefiero código claro y ownership de extremo a extremo.",
    location: "Palermo, CABA",
    distanceKm: 1.9,
    hourlyRate: 55,
    currency: "USD",
    rating: 4.96,
    reviews: 38,
    jobsCompleted: 54,
    skills: ["Java", "Laravel", "Python", "Back-end", "SQL", "APIs REST"],
    categories: ["dev"],
    photoUrl: "/avatars/ciro-maraton.png?v=202602011",
    contactWhatsappDigits: "5491126408197",
    contactEmail: "ciro.ferrario.labur@gmail.com",
    verified: true,
    online: true,
  },
  {
    id: "p-ivan",
    name: "Iván Xavier",
    age: 30,
    headline: "Ingeniero Informático · Software Engineer",
    bio: "Construyo productos web y mobile-first. Laburapp: match laboral tipo app de citas, en español rioplatense. Stack habitual: Next.js, TypeScript, diseño enfocado en UX.",
    location: "Buenos Aires, CABA",
    distanceKm: 0,
    hourlyRate: 40,
    currency: "USD",
    rating: 5.0,
    reviews: 3,
    jobsCompleted: 12,
    skills: ["Ingeniería de software", "Next.js", "TypeScript", "UX"],
    categories: ["dev", "marketing"],
    photoUrl: demoUserPhotoUrl,
    compactDetailPanel: true,
    contactWhatsappDigits: "5493541234567",
    contactEmail: "ivanxavi4@gmail.com",
    verified: true,
    online: true,
  },
  {
    id: "p1",
    name: "Lucía Fernández",
    age: 28,
    headline: "Asesora de ventas senior",
    bio: "Más de 5 años cerrando ventas B2B en SaaS. Disponible part-time.",
    location: "Palermo, CABA",
    distanceKm: 2.3,
    hourlyRate: 8500,
    currency: "ARS",
    rating: 4.9,
    reviews: 47,
    jobsCompleted: 62,
    skills: ["Ventas B2B", "Outbound", "HubSpot", "Negociación"],
    categories: ["ventas", "marketing"],
    photoUrl:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&q=80&auto=format&fit=crop",
    verified: true,
    online: true,
  },
  {
    id: "p2",
    name: "Martín Sosa",
    age: 35,
    headline: "Plomero matriculado · 24hs",
    bio: "Destapaciones, calefones, instalaciones. Voy a domicilio en zona norte.",
    location: "Vicente López",
    distanceKm: 5.8,
    hourlyRate: 12000,
    currency: "ARS",
    rating: 4.8,
    reviews: 134,
    jobsCompleted: 210,
    skills: ["Plomería", "Gasista", "Urgencias 24hs"],
    categories: ["plomeria", "gasista"],
    photoUrl:
      "https://images.unsplash.com/photo-1607990281513-2c110a25bd8c?w=800&q=80&auto=format&fit=crop",
    verified: true,
    online: false,
  },
  {
    id: "p3",
    name: "Carolina Méndez",
    age: 31,
    headline: "Veterinaria a domicilio",
    bio: "Consultas, vacunación y emergencias. Atiendo perros, gatos y exóticos.",
    location: "Belgrano, CABA",
    distanceKm: 3.1,
    hourlyRate: 15000,
    currency: "ARS",
    rating: 5.0,
    reviews: 89,
    jobsCompleted: 156,
    skills: ["Clínica menor", "Vacunación", "Domicilio"],
    categories: ["veterinaria"],
    photoUrl:
      "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=800&q=80&auto=format&fit=crop",
    verified: true,
    online: true,
  },
  {
    id: "p4",
    name: "Diego Ramírez",
    age: 26,
    headline: "Dev Full-Stack · Next.js / Node",
    bio: "Construyo MVPs y productos web. Disponible para proyectos por sprint.",
    location: "Remoto · GMT-3",
    distanceKm: 0,
    hourlyRate: 35,
    currency: "USD",
    rating: 4.9,
    reviews: 28,
    jobsCompleted: 31,
    skills: ["Next.js", "TypeScript", "Supabase", "Tailwind"],
    categories: ["dev"],
    photoUrl:
      "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=800&q=80&auto=format&fit=crop",
    verified: true,
    online: true,
  },
  {
    id: "p5",
    name: "Sofía Pereyra",
    age: 24,
    headline: "Paseadora de perros · Dog walker",
    bio: "Paseos grupales o individuales. Veterinaria estudiante. Caminito y Recoleta.",
    location: "Recoleta, CABA",
    distanceKm: 1.2,
    hourlyRate: 4500,
    currency: "ARS",
    rating: 4.95,
    reviews: 211,
    jobsCompleted: 480,
    skills: ["Paseos", "Cuidado", "Adiestramiento básico"],
    categories: ["paseo-perros", "veterinaria"],
    photoUrl:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800&q=80&auto=format&fit=crop",
    online: true,
  },
];
